### ISSUE TITLE
Support for named css colors

### ISSUE THREAD

**Issue by suchipi** [styled-components/polished#153]
It'd be nice if you could use helpers with named CSS colors, eg "white", "salmon", etc. Polished would need to have a map of names to "usable" colors. It could maintain its own list of colors, or use a package like `css-color-names`.

**Comment by bhough** [comment]
@suchipi Thank you for the suggestion. I'm assuming this would be so you could use named colors with the color mixins? Ideally what would these be mapped to? I'm assuming the hex values?

**Comment by suchipi** [comment]
Yeah, I was thinking the hex values; to be used with darken, desaturate, [etc](https://polished.js.org/docs/#color).

**Comment by bhough** [comment]
Definitely something we'd consider doing. The concern I have that would need addressed is to how to add that functionality to all the color mixins without bloating the size of those modules.

**Comment by suchipi** [comment]
What kind of size goals does the project have? It looks like my install of `polished.min.js` is 24KB.

Here's one example of a name-to-hex map (not sure if it's complete), that's 3.75KB uncompressed: https://github.com/bahamas10/css-color-names/blob/master/css-color-names.json

Something like this could be shrunk by removing whitespace, duplicated `#` characters, and converting 6-character hex codes to 3 characters where possible.

It's also possible to offload this work to the browser via `getComputedStyle`, but this would not work in node, and likely not work in jsdom. I was under the impression that it was a goal of this project to work in node/jsdom as well. Is that correct?

If there was a way to make this theoretical part of the codebase tree-shakable if unused, would that change the size requirements at all?

What if a "browser" build relied on `getComputedStyle`, but a "node" build relied on a map in the bundle?

Another approach would be to try to do this work with a babel plugin. However, that would not cover dynamic cases (it could only transform string literals).

**Comment by bhough** [comment]
Right now we don't have a size goal for the entire project as we want users to only import the modules they need. We also are aiming for this to be dependency-free.

Yes we definitely want it to work across the board, so `getComputedStyle` is not an option, and I don't want to fork the builds based on the target for one feature.

It would be tree-shakable as far as it would only be included if a color module that used it was imported. But without dynamic imports in ES6, there isn't really a clean way to drop the named color list on its own if it isn't used.

To be clear, I think we can get this to an acceptable state, just want to make sure we consider all the implications. That list you linked is complete, so that gives us a baseline. Would love to get a PR started and we can start iterating on the approach.

**Comment by nikgraf** [comment]
Really nice considerations!

**Comment by bhough** [comment]
Closed by #155. Thank you for the suggestion @suchipi

**Comment by suchipi** [comment]
Thanks!
