### ISSUE TITLE
`transparent` color not supported by functions

### ISSUE THREAD

**Issue by corbanbrook** [styled-components/polished#188]
Passing a color value of `transparent` into functions like darken causes an error.

`Error: Couldn't parse the color string. Please provide the color as a string in hex, rgb, rgba, hsl or hsla notation.`

However other color strings such as `white` work fine.

**Comment by bhough** [comment]
@corbanbrook This is because `transparent` does not have an associated color code. In order to act upon it with our color methods, it has to translate to a HEX or RGB value. All other color keywords work since they have associated HEX values. I'm not sure there is a universally accepted color representation for transparent (such as white or black at 0 opacity).

**Comment by bhough** [comment]
We will also be improving the error messaging in V2, I'll make a note we need to include color keywords (outside of transparent) as valid input types.

**Comment by corbanbrook** [comment]
I think it would make sense to support transparent as it is a valid color value in css but rather than treating it as black or white with 100% transparency, it should simply pass-through on all color functions like it does on sass/stylus.

Here is a sass example:

```sass
.hello {
  color: darken(transparent, 0.5);
}
```

```css
.hello {
  color: transparent;
}
```

**Comment by bhough** [comment]
This has been added to the V3 Roadmap (#354).
