### ISSUE TITLE
[docs] stand-alone imports advice

### ISSUE THREAD

**Issue by Andarist** [styled-components/polished#207]
When using rollup or webpack2+ does this advice really matters? Im not 100% sure, but according to [simple example](https://goo.gl/EM9UpH) even importing all with a wildcard wont prevent es module aware bundlers to statically analyze imports and their usage, so proper tree shaking should be still possible.

**Comment by bhough** [comment]
Thanks for raising this @Andarist. I will revisit this as part of #205.

**Comment by bhough** [comment]
@Andarist Importing with the wild card has the result currently with webpack/rollup because of how tree-shaking works in both. 

However, as browsers start to properly implement ES6 modules (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) `import * as polished from 'polished', would result in the entire library being imported as the spec is currently written.

In order to avoid encouraging a bad habit that could bite the user down the road, we want to try to encourage the proper import style, even if right now it may not matter.

**Comment by Andarist** [comment]
@bhough Fair point. It got me thinking though - actual module file will have to be downloaded anyway (as a whole) and probably even parsed so only a 'cherry-picked' function can be imported from the other module, right?

**Comment by bhough** [comment]
@Andarist my guess is that a build step will be required, but how we build will be quite a bit different. Could be possible it identifies what modules need to be "shipped" without the concept of bundling them in the way we think today. Code-splitting and http2 will also continue to have an impact on this. My hope would be that the solution would follow the modules spec without doing it's own additional thing, but it is probably too early to tell.
