### ISSUE TITLE
Using props in rbga

### ISSUE THREAD

**Issue by btmdave** [styled-components/polished#214]
We're trying to use `rbga` with props provided by styled-components theme provider.  I.e.:

`background: ${rgba(props => props.theme.white, 0.7)};`

This gives an error `Passed invalid arguments to rgba,...` Is there anyway around this?

**Comment by bhough** [comment]
Hi @btmdave, yes you can use props in any of our helpers, just need to tweak your syntax. You are getting the error because you are passing a method as opposed to the prop itself. See: https://github.com/styled-components/polished/issues/180#issuecomment-315307164.

Let me know if you have any other questions.
