### ISSUE TITLE
helper for multiplying font-sizes with units

### ISSUE THREAD

**Issue by sagiavinash** [styled-components/polished#223]
Feature Request: (want to contribute)

i am converting my sass codebase to styled components and i use these sass helpers to multiply pixel font sizes

> roun­d($­num­ber) Rounds a number to the nearest whole number.
> 
> ceil­($n­umb­er) Rounds a number up to the next whole number.
> 
> floo­r($­num­ber) Rounds a number down to the previous whole number.
> 

currently to achieve this, i did
```
import { stripUnit } from 'polished';

const fontSizeBase = '14px';
const fontSizeLarge = `${Math.ceil(stripUnit(fontSizeBase) * 1.25))}px`;
```

a generic helper can be something like this
```
// polished helpers
const multiplyFontSize = (multiplier, fontSize) => {
  const value = stripUnit(fontSize);
  const unit = fontSize.split(value)[1];

  return `${value * multiplier}${unit}`;
};

const roundFontSize = (criteria, fontSize) => {
  const value = stripUnit(fontSize);
  const unit = fontSize.split(value)[1];

  return `${Math[criteria](value)}${unit}`;
};

// helper usage
import { roundFontSize, multiplyFontSize  } from 'polished';

const fontSizeBase = '14px';
const fontSizeLarge = roundFontSize('ceil', multiplyFontSize(1.25, fontSizeBase));
```
any thoughts on this?

**Comment by sagiavinash** [comment]
@bhough any decision or future course of action. I am new to OSS can you guide me?

**Comment by bhough** [comment]
@sagiavinash sorry for the delayed response. So it seems like the helper that would be useful is a general one that allows us to do math with CSS values generally as you've described for the specific font use case. Other issues like #234 are also trying to get at this problem.

So I think a good first step would be to talk through a proposed api for a more general set of helpers for doing math on CSS units. It may take a few attempts as I think I have a firm grasp on the problem, but less firm idea of how we should solve it.

**Comment by caribou-code** [comment]
Is there no progress with this? I recently switched from SCSS where this was core functionality and fundamental to achieving theming, styling consistency and DRY code throughout a web app. I was very surprised to see Polished doesn't already do this.

As a temporary measure, I've implemented a `calculate.js` util in my project to multiply and divide values with units, but this is far from ideal because I have to import this into so many files where I already have polished.

```
// @flow

export const stripUnit = (value: string): ?number => {
  const match = /[0-9]+\.?[0-9]*/.exec(value);
  return match ? Number(match[0]) : match;
};

export const getUnit = (value: string): string => {
  const match = /[a-z]+|%/i.exec(value);
  return match ? match[0] : '';
};

export const multiply = (multiple: number, value: string): ?string => {
  const number = stripUnit(value) || 0;
  const unit = getUnit(value) || '';
  return `${number * multiple}${unit}`;
};

export const divide = (denominator: number, value: string): ?string => {
  const number = stripUnit(value) || 0;
  const unit = getUnit(value) || '';
  return `${number / denominator}${unit}`;
};
```

Usage looks like:

```
import { multiply } from '../util/calculate';

export default styled.div`
  font-size: ${({ theme }) => multiply(2, theme.fontSize)}
`; 
```

**Comment by bhough** [comment]
@caribou-code There has not. We've had other modules that have garnered more traction that we are about to release in 2.0 We look to upvotes on the module request issues as an indicator of interest, and this has not garnered much. Especially as support for `calc` has gotten better.

That being said we are always open to PRs and seems like you've done some of the work towards a helper, and we'd be glad to look at it if you submitted something.

I'm not sure I understand some of your comments about it being an impact on DRY code or your concern about the extra imports. Is there a fundamental difference between importing your helper or ours? If you are importing all of `polished` into your modules you may be bringing more code on then you need. Otherwise, if you are just importing parts of it into the module, there isn't much difference between importing them from polished, or your own module. You could actually cut some duplicate code out though by using our `stripUnit` helper (and soon one for getting units as well) into your calculation helper.

re:DRY while I see some value in these helpers with this, a DRYer version would be to do the math once in your theme file and setup different variables for commonly used sizes and use those, instead of calculating it in the styling like in your example. 

I'm open to more discussion, but I'm not sold yet that the specific problems you've laid out for this not being included are greatly solved by this one helper. In general we aren't always looking to cover every single use case, but in those cases provide building blocks to create your own that suite your needs.

**Comment by caribou-code** [comment]
@bhough It looks like someone already did a PR a while ago but it didn't get further: [#227](https://github.com/styled-components/polished/pull/277)

To clarify what I meant by DRY, I'm talking about an alternative technique that allows JS to do the maths by storing theme variables as numbers without units. But with this method you have to then apply the unit on every usage, which is not DRY and can cause trouble down the line.

With that in mind, I can only see 2 good ways to do calculations. Either using CSS calc, or doing this in the JS. My problem with using CSS calc is the calculations can get fairly complicated and long, which feels a little weird creating these calculations in a string. I also wonder about performance implications if there are many of these in a component.

As for pre-calculating the maths in theme files, I don't feel this is flexible enough for large scale apps.

**Comment by tobilen** [comment]
i consider it an elementary feature as well. i've taken the code from my PR and implemented it in our internal tooling library. if there is interest to get this merged in polished, i can reopen the PR?

**Comment by caribou-code** [comment]
Perhaps worth noting another experience I've had today. I needed to use pythagoras theorem to calculate part of a CSS layout. When using CSS calc you can only use basic operators (+, -, *, /) which means square root is not possible. When working with a number with a unit, this means Polished has no way to handle this, and I can't use CSS calc. Leaves me a bit stuck if I want to write DRY and scalable code, unless I implement my own method for handling this.

**Comment by bhough** [comment]
Added to V3 Roadmap (#354).

**Comment by tobilen** [comment]
@bhough i've reopened my PR ( https://github.com/styled-components/polished/pull/277 ) and will update it either today or over the weekend )
