### ISSUE TITLE
Consider adding a sanitation helper.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [styled-components/polished#230]
`styled-components` [suggests that input be sanitized](https://www.styled-components.com/docs/advanced#security).  While some of it will have to be left to the individual developer, `polished` could have a function or two to help validate input, like a regex that determines whether or not some input is a valid hex or rgb color.

**Comment by mxstbr** [comment]
I like that idea, what do you think @bhough? I'd love to be able to point people to polished as a means to sanitize/verify some inputs.

**Comment by bhough** [comment]
Definitely open to this as long as we do it in a way that isn't specific `styled-components`. @mxstbr any initial thoughts on the type of issues we need to look out for, or common types of user input we need to sanitize?

**Comment by nelix** [comment]
I'm interested in this, but I think some more definition is needed.
Are we just talking about user input that would end up in css? Or are we talking about a more generic data validation library for form inputs?
If we just want to validate colors, urls, etc we already have parseToHsl like functions that might be safe? Or maybe could be made safer? A url sanitize function (blocking other css values, blocking ;, blocking data and js urls?), Maybe a generic valueThatDoentXSS() function?

Or are we talking full access to event.target.value/onChange?
```js
const {validate, isValid} =  map(
  styled.validators.isRequired,
  styled.validators.number,
  styled.eventHelpers.preventDefault,
);

styled.input.attr({
  something: 'cool',
  onChange: validate,
})`
${validOr(`
  color: green;
`,`
  color: red;
`)}
```
Or generic
```js
<input onChange={validate} style={{...things!}}}/>
```
I think these would have issues with chaining onChange events, but something workable could be done, and helpers for preventDefault, stopPropagation could be provided... and I can't think of a decent api.

But I do feel its kinda out of the scope of polished, whats a word like polished for more functional tasks? Refined?

I guess the more polished style of validation would be visual feedback..

```js
styled.input`
  color: ${polished.validator.isUrl('value', 'green', 'red')};
`
```
Where 'value' is the prop to connect with.

I'm feeling pretty unsure about these, especially since polished doesnt provide basic prop getters or other things dealing with props/state.
Example of a pretty useful getter:
```js
import styled from 'styled-components';

const getProp = (prop) => (props) => props[prop];

const Input = styled.input`
  color: ${getProp`color`};
`
```
Its a simple function, but its really useful avoiding repetition, and it could be expanded on to add validators...

```js
const Input = styled.input`
  color: ${getProp`color`.isRequired.isSafeColor};
`
```

**Comment by bhough** [comment]
@nelix 

Let's see if I can answer all these questions:

1. We only want to do this for user-provided CSS values and don't want to be concerned with being a general input sanitizer.
2. For starters I think we should stick to sanitization vs. validation. So making sure something is a sanitized value vs making sure something is a valid color for example. I'm still putting thought into how I want to handle validation of CSS values (not just user inputed).
3. On the getter front there is already https://github.com/diegohaz/styled-tools for styled-components. We try to keep polished library agnostic and other libraries handle how props are passed in a bit differently or offer their own getter implementation.

**Comment by bhough** [comment]
@mxstbr is this still a necessity given the current recommendation to use: https://github.com/mathiasbynens/CSS.escape?

**Comment by bhough** [comment]
@wtgtybhertgeghgtwtg closing this with https://github.com/mathiasbynens/CSS.escape as the recommended solution for this.
