### ISSUE TITLE
Flow unable to find polished module

### ISSUE THREAD

**Issue by johnryan** [styled-components/polished#239]
- `polished` version: 1.6.1
- `JSS-in_CSS` library and version: styled components 2.1.2
- Any relevant JS library and version: flow-bin 0.52

For some reason flow is having issues with `polished`. I've tried adding `.*/node_modules/polished/.*` but it seems to have no effect.

My whole ignore section for completeness

```
[ignore]
.*/node_modules/styled-components/.*
.*/node_modules/polished/.*
.*/node_modules/fbjs/.*
.*/node_modules/.* 
```

What you are seeing:
```
import { rgba } from 'polished';
                          ^^^^^^^^^^ polished. Required module not found
```
What you expected to see:

Flow should not have issues with the polished library

**Comment by bhough** [comment]
@johnryan it is because of `.*/node_modules/.*` inside your ignore block. Anything that comes with types onboard in your `node_modules` folder (including polished) will be ignored: https://github.com/facebook/flow/issues/2092

The reason that adding `.*/node_modules/polished/.*` doesn't do anything is because that is not an error from processing polished through flow but an error from flow itself not being able to resolve types for polished.

If you adjust your ignores so polished isn't ignored it will pick up its types just fine, (ideally by not blanket ignoring node_modules) Otherwise if you are using something like [flow-typed](https://github.com/flowtype/flow-typed) you can generate an empty stub for polished to get rid of the error (but you won't get typings that way). We will eventually provide separate libdefs you can install via flow-typed as well, but given that not everyone is familiar with this process we decided to start by providing them on board instead.

**Comment by johnryan** [comment]
@bhough thanks for the response. I am actually using `flow-typed` to generate empty stubs but for some reason it doesn't generate the empty stub for `polished` (regardless of the flowconfig setup, even though it does for other libraries). Does that sound like an issue with `flow-typed` or is there some other config needed to get it to generate that stub?

**Comment by bhough** [comment]
@johnryan of course 👍 

So `flow-typed` only installs stubs for modules that a) are not typed and b) it doesn't have libdefs for in it's repo. Because polished is typed out of the box it won't generate a stub.

You can force this behavior with `flow-typed create-stub polished@1.6.x`. However, I would suggest fixing your ignores not to include `polished` so you get the types we have already built in.

**Comment by johnryan** [comment]
@bhough got it, that makes sense. Removing those ignores seems to fix the import issue but introduces a whole bunch of other flow errors. For example: 

```
Error: node_modules/polished/lib/color/toColorString.js.flow:68
 68:   if (isRgb(color)) return rgb(color)
                                ^^^^^^^^^^ function call
 68:   if (isRgb(color)) return rgb(color)
                                    ^^^^^ object type. This type is incompatible with
 30: function rgb(value: RgbColor | number, green?: number, blue?: number): string {
                         ^^^^^^^^^^^^^^^^^ union: RgbColor | number. See: node_modules/polished/lib/color/rgb.js.flow:30
```

Is this an issue with the `.flowconfig` or an unrelated typing issue in polished?

**Comment by bhough** [comment]
@johnryan try upgrading to the latest flow 0.53.1 I believe it is, and see if those go away. Not seeing those on my end.

**Comment by johnryan** [comment]
@bhough that resolved the issue thanks!

**Comment by bhough** [comment]
@johnryan no problem. Glad I could help. Flow is still quite finicky for third party libraries, especially moving between versions.
