### ISSUE TITLE
Rollup isn't processing spread operator in normalize.js

### ISSUE THREAD

**Issue by stephenway** [styled-components/polished#279]
- `polished` version: master

Mixin/Helper/Shortand you were using and how you were using it:

I wanted to setup my fork so I could begin contributing to the project.

```shell
npm install
```

What you are seeing:

![image](https://user-images.githubusercontent.com/38894/34279362-4d0eade4-e665-11e7-8423-a15929fab701.png)

This leads me to believe that even though rollup has a spread operator plugin, it still fails to recognize it during the bundling process. Specifically this is happening in normalize.js

![image](https://user-images.githubusercontent.com/38894/34279485-01c23670-e666-11e7-9abb-88d7d4e964b7.png)

At this point I thought it would be useful to try building docs to run the webserver, but that didn't help.

What you expected to see:

* Expected to see the project to build and docs webserver spin up without issue.
* Also, not sure why my VSCode isn't liking the flow types, but I can focus on that.

Reproduction:

* Just clone my fork for the same version of master: https://github.com/stephenway/polished
* Then try to `npm install` and `npm build`, etc.

**Comment by bhough** [comment]
Sorry @stephenway been on vacation and traveling for the past few weeks. I will take a look at this this weekend, and initial pull worked for me so I need to see what might be going on with your setup or if we have some version off in the lockfile that is not loading proper plugins, or something of that sort.

**Comment by stevenbenisek** [comment]
I can confirm this issue exists when running `npm install`. Because of *yarn.lock* you won't run into the same issues using `yarn install`. However, if you delete *yarn.lock* running `yarn install` will cause the same error as `npm install`. Taking a closer look at the newly generated *yarn.lock* reveals that a lot of dependencies are installed with a different version compared to the current lockfile, e.g:

> babel-plugin-transform-object-rest-spread: 6.23.0 -> 6.26.0
> babel-core: 6.24.0 -> 6.26.0
> rollup-plugin-babel: 3.0.2 -> 3.0.3
> rollup: 0.50.0 -> 0.50.1
...

I haven't looked into what exactly is causing the problem, but from what I'm seeing it likely has something to do with incompatible or buggy dependency versions. I'll see if I can find the issue because at some point this will affect `yarn install` as well.

**Comment by stevenbenisek** [comment]
Found the issue. 

With the current lockfile [rollup-plugin-commonjs 8.2.1](https://github.com/rollup/rollup-plugin-commonjs/tree/v8.2.1) is installed. 
Without lockfile [rollup-plugin-commonjs  8.2.6](https://github.com/rollup/rollup-plugin-commonjs) is installed. 

In 8.2.6, *src/mixins/normalize.js* is parsed by [Acorn](https://github.com/acornjs/acorn): https://github.com/rollup/rollup-plugin-commonjs/blob/master/src/transform.js#L31
In 8.2.1 there was an early exit so *src/mixins/normalize.js* was never parsed by [Acorn](https://github.com/acornjs/acorn): https://github.com/rollup/rollup-plugin-commonjs/blob/v8.2.1/src/transform.js#L44

Because [Acorn](https://github.com/acornjs/acorn) doesn't support the spread operator in object literals (https://github.com/acornjs/acorn/issues/388) the polished build fails.

**Comment by stevenbenisek** [comment]
I'm happy to raise an issue at https://github.com/rollup/rollup-plugin-commonjs/. Untill this gets fixed I suggest locking the version to 8.2.1 in the polished package.json to prevent future failure:

```
"rollup-plugin-commonjs": "8.2.1",
```

instead of 

```
"rollup-plugin-commonjs": "^8.2.1",
```

**Comment by stevenbenisek** [comment]
Are you ok with this approach @bhough?
If so, I'll create a PR.
Maybe we should document why the version is locked?

**Comment by bhough** [comment]
@stevenbenisek Thank you for digging into this, I suspected it might be something like that.

I'm fine with this approach if you want to create a PR as a fix (so it bumps the patch version).

That would be awesome if you could raise an issue on the plugin and link it back here, and we can use that as documentation.

**Comment by stevenbenisek** [comment]
Referencing https://github.com/rollup/rollup-plugin-commonjs/issues/275

**Comment by stephenway** [comment]
@stevenbenisek Thanks for straightening this out!

**Comment by gary1410** [comment]
Hmm...I'm not so sure this works.  I just locked plugin-common-js to 8.2.1 and it doesn't work.  I also can't get the external spread operator package to work.

```
{
  "name": "id-stitch-rollup",
  "version": "1.0.0",
  "description": "to create a bundle file",
  "main": "bundle.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-plugin-external-helpers": "^6.22.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "rollup-plugin-babel": "^3.0.3",
    "rollup-plugin-commonjs": "8.2.1",
    "rollup-plugin-eslint": "^4.0.0",
    "rollup-plugin-node-builtins": "^2.1.2",
    "rollup-plugin-node-globals": "^1.1.0"
  },
  "dependencies": {
    "axios": "^0.17.1",
    "fingerprintjs2": "^1.5.1",
    "hash.js": "^1.1.3",
    "q": "^1.5.1",
    "rollup-plugin-node-resolve": "^3.0.0",
    "rollup-plugin-serve": "^0.4.2"
  }
}
```

rollup.config.js

```import livereload from 'rollup-plugin-livereload';
import serve from 'rollup-plugin-serve';
import babel from 'rollup-plugin-babel';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import builtins from 'rollup-plugin-node-builtins';
import globals from 'rollup-plugin-node-globals';

export default {
    input: 'src/main.js',
    output: {
        file: 'bundle.js',
        format: 'iife',
        name: 'main',
        sourcemap: 'inline'
    },
    plugins: [
        builtins(),
        serve(),
        livereload(),
        resolve({main: true}),
        commonjs(),
        globals(),
        babel({
            plugins: ['external-helpers', 'transform-object-rest-spread'],
            exclude: 'node_modules/**'
        })
    ]
};```

.babelrc

```
{
  "presets": [
    [
      "env",
      {
        "modules": false
      }
    ]
  ],
  "plugins": [
    "external-helpers",
    "transform-object-rest-spread"
  ]
}
```

**Comment by bhough** [comment]
@gary1410 I cloned a fresh copy of the repo after @stevenbenisek's changes and had no issue building with either `yarn` or `npm`. Did you pull the latest and then delete `npm-modules` before running `install`? Are you doing this with yarn or npm? What errors are you seeing?
