### ISSUE TITLE
Use case for sending numbers to position shorthand

### ISSUE THREAD

**Issue by lcsrinaldi** [styled-components/polished#285]
Mixin/Helper/Shorthand you were using and how you were using it:

The shorthand is `position`

```javascript
const positionProp = ({ pos, top, right, bottom, left }) => {
  const values = [top, right, bottom, left];
  return position(
    pos,
    ...values.map(value => (value ? `${value}px` : null)),
  );
};

const Panel = Flex.extend`
  background-color: ${props => props.theme.grey050Color};
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.16);
  ${positionProp};
`;
```

---

My issue is not to report a bug, is to actually ask what's the use case of passing numbers to the `position` shorthand? The function doesn't add any unit to it's result, so why would I send numbers?

**Comment by bhough** [comment]
Hi @lcsrinaldi, thanks for the question. It allows numbers for two reasons. One is so you can pass `0` as a number instead of a string:

```javascript
const styles = {
  ...position('absolute', 0, '24px', '36px', 0)
}
```
The second is to make it more friendly for use in React Native which uses unitless values in styling. This saves users from having to pass unitless numbers as strings.

**Comment by lcsrinaldi** [comment]
Hey @bhough, makes sense! I'll close this then, thanks for your quick answer.
