### ISSUE TITLE
normalize in TypeScript outputs [object Object]

### ISSUE THREAD

**Issue by seleckis** [styled-components/polished#329]
As such functions as `injectGlobal` does not work with TypeScript correctly (see #261 ) I had to create a function which executes injectGlobal.
```tsx
import {normalize} from 'polished';
import * as styledComponents from "styled-components";

const {
  injectGlobal,
} = styledComponents;

const globalStyle = (style: string) => injectGlobal`${style}`;

globalStyle(`
  ${normalize()}
  body {
    font-family: Lato;
    margin: 0;
  }
`);
```
Unfortunately, `normalize()` outputs `[object Object]` instead of normalize css code:
```css
[object Object] body{font-family:Lato;margin:0;}
```

**Comment by vhfmag** [comment]
I believe this is not a bug. `injectGlobal` is a [tagged template literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals): a function called without parenthesis, with a template literal ``injectGlobal`${normalize()}` ``.

Functions that receive a template literal as a parameter (as in ``globalStyle(`${normalize}`)``) differ from tagged template literals because, while in the former the result of `normalize()` is directly converted to `string (therefore resulting in `[object Object]`), in the later, the injectGlobal functions receive the result of normalize() and interpolates it itself.

The original typing of injectGlobal is:
```ts
export type InterpolationValue = string | number | Styles | FalseyValue | StyledComponentClass<any, any>;
export type SimpleInterpolation = InterpolationValue | ReadonlyArray<InterpolationValue | ReadonlyArray<InterpolationValue>>;
export injectGlobal(strings: TemplateStringsArray, ...interpolations: SimpleInterpolation[]): void;
export interface Styles {
  [ruleOrSelector: string]: string | number | Styles;
}
```

The problem arises because, in the Typescript type definitions, the return type of normalize is `Object`.

A solution is to re-export the normalize function with a return type compatible with styled-components' `Styles`, and as far as I know, polished returned styles are compatible with the interface.

**Comment by bhough** [comment]
@seleckis I was able to confirm that @vhfmag's theory is true. The improper usage as a tagged template literal is what is causing your issue.

You should also keep an eye on #331 as that will provide better Flow/Typescript compat with `styled-components`.
