### ISSUE TITLE
Method Chaining

### ISSUE THREAD

**Issue by seanemmer** [styled-components/polished#333]
Feature Suggestion (Polished 1.93, Styled-Components 3.3.3)

Introduce ability to chain polished methods.

**Current**
const wrapped = setSaturation(0.5, lighten(0.45, 'red'))

**Proposed**
const chained = polished('red').lighten(0.45).setSaturation(0.5)

Happy to work on a PR if this doesn't already exist in some form and people think it will be useful.

**Comment by bhough** [comment]
@seanemmer Our preferred method for this is via composition, which all our color functions currently support. 

@nikgraf Covers how that all works in this talk: https://www.youtube.com/watch?v=qJgff2spvzM

For your example it would look something like this:

```javascript
import { compose } from 'ramda' // Replace with any compose() function of your choice
import { lighten, SetSaturation } from 'polished'

// Create setTone() helper
const setTone = compose(lighten(0.45), setSaturation(0.5))
const newRed = setTone('red')
```
We made a specific decision to go this route over the model other libraries use that require you to instantiate a color object in order to modify it.
