### ISSUE TITLE
fluidRange & between don't return the proper calculation when from/toSize don't have the same units as min/maxScreen.

### ISSUE THREAD

**Issue by EarthlingDavey** [styled-components/polished#445]
- `polished` version: 3.4.0
- `JSS-in_CSS` library and version: styled-components 4.2.0

Mixin/Helper/Shorthand you were using and how you were using it:

```
h4 {
    ${fluidRange(
      {
        prop: 'font-size',
        fromSize: 1rem,
        toSize:4rem
      },
      '400px',
      '1000px'
    )}
  }

```

What you are seeing:

The font-size between screen sizes 400px and 100px is not calculated correctly.

What you expected to see:

A smooth change in font size between 400px and 1000px screen widths

Reproduction:

https://codepen.io/daveybrown/pen/GaLXVE

**Comment by bhough** [comment]
This will be addressed in v4.

**Comment by Grsmto** [comment]
Just FYI, there is the same issue with the `between` function.

**Comment by bhough** [comment]
@Grsmto Yep, `fluidRange` is just a wrapper that adds functionality to `between`.

**Comment by kjbrum** [comment]
If it's not known already, when using rem units for the `fromSize`/`toSize` and the min/max screen sizes, it works correctly.

**Comment by bhough** [comment]
The issue here is not specifically with `rem`, but is instead with using a different unit of measure for the screen units and the unit you rule you want to be fluid (in this case `font-size`.)

Ultimately, we have decided to make this an error. Given all the potential cases needed to normalize the two units as well as the decisions we will have to try and make on behalf of the user (which unit to convert to/from, what base to use for em/rem, etc..), we would have to dramatically overload the module to account for all the conversion checks and the conversions themselves. 

We do offer some helpers to convert to `rem` and `em` for the cases where you might not have control over the units.

**Comment by bhough** [comment]
This has been addressed in v$ which is now in beta and will be released in the coming weeks:

`npm install polished@next`
`yarn add polished@next`
