### ISSUE TITLE
Setting Default Dark & Light Values for readableColor

### ISSUE THREAD

**Issue by moshemo** [styled-components/polished#461]
Is it possible to set default dark and light values for the readableColor function (rather than have to manually set them each time I want to use them)?  

If so, is there documentation on how to do that?

Thanks.

**Comment by bhough** [comment]
It is not (other than the built-in white/black defaults). Because these are meant to be used in isolation, we wouldn't be able to write a good way to set and store those custom defaults. 

That being said, you could write a lightweight wrapper around `readableColor` that stores those defaults and use that wrapped version in all your components.
