### ISSUE TITLE
Problematic

### ISSUE THREAD

**Issue by jaydenseric** [styled-components/polished#58]
I don't want to dampen enthusiasm of everyone here, I respect you all very much. But I don't think the direction this project is going is a good idea.

This is the sort of project that would appeal to newer developers, the sorts who a less likely to understand tree shaking and destructured imports. Here is what a disappointing portion of users will do:

```
import polished from 'polished'
```

[This line](https://github.com/styled-components/polished/blob/master/src/index.js#L29) will let them. They will pull in the entire library to the client bundle.

**Suggestion:** Remove the default export, force users to only import what they need.

Then on some button somewhere, the user will throw in `polished.timingFunctions('easeInCubic')`, because the name was familiar from some other past library and they liked it. Even if they used a destructured import for `timingFunctions`, they now also have every timing function they _didn't_ use in their bunde, [a hefty set of values](https://github.com/styled-components/polished/blob/master/src/mixins/timingFunctions.js#L4). In my experience, 99.999% of the time the [standard keywords](https://www.w3.org/TR/css3-transitions/#transition-timing-function-property) are sufficient.

**Suggestion:** Remove `timingFunctions`, or refactor the module to export each string separately to allow destructured imports. This will simplify the module, no function necessary.

Clearfix as a concept is dead, and should not be supported in any new libraries. Floats are bad practice now we have robust layout options like flexbox.

**Suggestion:** Remove `clearfix`.

For some reason most of the CSS in JS libraries are a let down in regards to automatically vendor prefixing `::selection` and `::placeholder`. This should just work automatically, the solution is not to manage mixins in a library like this with [hardcoded vendor prefixes](https://github.com/styled-components/polished/blob/master/src/mixins/hiDPI.js#L34) that do not respect a user's browserslist config or respond to user agent.

**Suggestion:** Don't hardcode vendor prefixes, remove `selection`, `placeholder`, `HiDPI` and other relevant APIs.

I can't see elegent use cases for helpers such as `em`. `em` and `px` are different CSS units with different uses. Developers should use the right one in the right circumstance. I almost never use `px` for anything. Thing is, such a small helper has [4 large error strings that won't minify](https://github.com/styled-components/polished/blob/master/src/helpers/em.js#L37).

**Suggestions:** Remove `em`. Is it possible to make all the other developer warnings only appear in dev bundles, like with React?

Regarding color utilities, see [this comment](https://github.com/styled-components/polished/issues/44#issuecomment-266948144).

**Suggestion:** It would be best for CSS in JS libraries to treat it the same as vendor prefixing: Users just follow the spec within the rule strings. Because this processing would add a _lot_ to a client side bundle, it should be opt-in or handled by a plugin.

I can't help but think whatever few utilities still make sense might be better off published separately to NPM. With CSS, almost any change is a breaking change to a meticulously tested front end. The bigger this library gets, the riskier updating for a particular bugfix becomes.

A few years ago, I standardised Bourbon for a team. After a year or so of heavy use, I banned it. We have always banned Bootstrap and Foundation. CSS libraries are generally wasteful, introduce unnecessary complexity and isolate developers from the CSS that actually runs in a browser.

**Comment by mxstbr** [comment]
I feel like there is a misunderstanding here, and I'm going to try to clear it up:

**This library isn't for you**, the power user, the CSS expert, the fully fledged veteran of the web who's been writing code for a dozen years and knows everything.

This library is for intermediate developers who have used Sass/Less/Stylus for a few years or maybe even have a legacy codebase. They want to switch to CSS-in-JS, either a pre-existing codebase or for a new project, but they can't because they use `@includes clearfix` everywhere and have no idea what to do with that!

This bridges that gap.

Now, you might say "They should just write better CSS" or "The libs should have a proper autoprefixer" and that's a totally fair point.

The issue is, that's not going to happen, and it stifles the growth of CSS-in-JS. So by building this library we bridge the gap and increase the adoption of styles in JS libs.

----

To respond to your individual suggestions:

> Remove the default export, force users to only import what they need.

Been thinking about this too, we definitely should get rid of that line! I'll also be forking the `lodash-webpack-plugin` and allowing users to make sure everything they don't need is kicked out by rewriting the imports.

> Suggestion: Remove timingFunctions, or refactor the module to export each string separately to allow destructured imports. This will simplify the module, no function necessary.

I don't see the value in this, the "hefty set of values" are literally 25 LoC. I'd happily take a PR exporting them all separately though, if the UX stays the same! Not quite sure how that'd work though.

> Clearfix as a concept is dead, and should not be supported in any new libraries. Floats are bad practice now we have robust layout options like flexbox.

Sure, you say that. You might not care about IE in your company, that's great! Happy for you. Sadly, a lot of people still have to support IE and/or haven't learned flexbox, both of which are totally valid reasons to use a clearfix.

Again, this library isn't meant for power users like yourself – you don't need it.
This is meant for people coming from a legacy Sass project, wanting to switch to CSS-in-JS and no idea what to do with all of their `@include clearfix` stuff.

> autoprefixing _should_ just work automatically

It doesn't, so we have them 😊 As soon as it works automatically all across the board we can think about removing them, until then I don't see a reason to.

*In case you're wanting to put the blame on the CSS-in-JS libraries, I'd love if you could write a fully compliant, user agent respecting autoprefixer for the browser that has less than 1k gzip + min. (or even 0.5kb) Good luck.*

*Since that's not happening, library authors have a choice: either they bloat their libs with 25kb of autoprefixing stuff to make sure they respect the user agent and blabla, or they do it in 10 LoC and only cover 95%. Until there's a better solution, choice two will always be what they do.*

> I can't see elegent use cases for helpers such as em. em and px are different CSS units with different uses. Developers should use the right one in the right circumstance. I almost never use px for anything.

That's great!

Again, you're a power user. There's a reason why this exists in pre-processors, and that is that designers will always give you pixel values. You will get a sketch file that says "This button is 10px from the other button" Instead of manually converting every. single. one. of them to `em` and putting that directly into the CSS, you just use `em('10px')` and that's it!

> Users just follow the spec within the rule strings. Because this processing would add a lot to a client side bundle, it should be opt-in or handled by a plugin.

I didn't know there was a spec for that, and I totally agree we should follow it! No doubt about it.

In terms of opt-in or making that a plugin – **this is literally an opt-in plugin**. We specifically didn't add support for this in our lib.

Literally nobody forces you to use this, ever. If you don't need it, perfect! Don't use it. That's great! Happy for you!

There is people that will rely on these functions to exist when they switch over from Sass, no matter if they have a pre-existing codebase or not, so we provide them. We bridge that gap to help increase the adoption of CSS-in-JS.

**Comment by nikgraf** [comment]
@mxstbr spot on

Let me emphasis once more we should not have a default export like suggestion @jaydenseric, but you know my position on this already and seems like you are on it anyway 🙂

**Comment by bhough** [comment]
> Let me emphasis once more we should not have a default export

@nikgraf already opened an issue for this #60 and it should be addressed as part of #57
