### ISSUE TITLE
Lighten red color dont work

### ISSUE THREAD

**Issue by lucasmoura-boticario** [styled-components/polished#587]
- `polished` version: 4.1.3
- `styled-components` : 3.3.0
- `React`: 16.3.2

## Mixin/Helper/Shorthand Usage

```javascript
background-color: ${lighten(0.5, "#f00")};
```

## What You Are Seeing

Lighten dont work red colors

## What You Expected To See

Lighten red color

## Reproduction

https://codesandbox.io/s/smooth-ui-example-forked-sg8iw?file=/src/index.js

**Comment by bhough** [comment]
@lucasmoura-boticario Thank you for submitting this issue. Lighten is working as intended here. You can only lighten certain colors so far before they become white. Because of the lightness of your original color, going past `0.4` as your first parameter value turns this particular color white. If you changed it to `0.4`, for example, you would see a lighter shade of your original red.
